DoAnTotNghiep_WebMinhChau/Areas/Admin/Models/NhanVien.cs
namespace DoAnTotNghiep_WebMinhChau.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Web.Mvc;

    [Table("NhanVien")]
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            DanhGiaSP = new HashSet<DanhGiaSP>();
            PhieuThu = new HashSet<PhieuThu>();
            TaiKhoan = new HashSet<TaiKhoan>();
        }

        [Key]
        [StringLength(10)]
        [Required(ErrorMessage = "Mã nhân viên không được để trống.")]
        [Remote("CheckMaNVExists", "NhanVien", ErrorMessage = "Mã nhân viên đã tồn tại.")]
        public string MaNV { get; set; }

        [StringLength(50)]
        [Required(ErrorMessage = "Họ tên không được để trống.")]
        public string HoTen { get; set; }

        [Range(1900, int.MaxValue, ErrorMessage = "Năm sinh không hợp lệ. Năm sinh không được lớn hơn năm hiện tại.")]
        public int? NamSinh { get; set; }

        [StringLength(50)]
        public string DiaChi { get; set; }

        [StringLength(20)]
        public string GioiTinh { get; set; }

        [Required(ErrorMessage = "Số điện thoại không được để trống.")]
        [StringLength(10, ErrorMessage = "Số điện thoại phải có độ dài chính xác 10 ký tự.")]
        [Phone(ErrorMessage = "Số điện thoại không hợp lệ.")]
        [Remote("CheckPhoneExists", "NhanVien", ErrorMessage = "Số điện thoại đã được sử dụng.")]
        public string SDT { get; set; }
        [StringLength(100)]
        public string TrangThai { get; set; }


        [Column(TypeName = "date")]
        public DateTime? NgayVaoLam { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaSP> DanhGiaSP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThu> PhieuThu { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoan { get; set; }
    }
}

DoAnTotNghiep_WebMinhChau/Models/NhanVien.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DoAnTotNghiep_WebMinhChau.Models
{
    public class NhanVien
    {
        [Key]
        [Column(TypeName = "char")]
        [StringLength(10)]
        public string MaNV { get; set; } // Mã nhân viên, khóa chính, tối đa 10 ký tự

        [StringLength(50)]
        public string HoTen { get; set; } // Họ tên nhân viên, tối đa 50 ký tự

        public int? NamSinh { get; set; } // Năm sinh nhân viên, có ràng buộc kiểm tra

        [StringLength(50)]
        public string DiaChi { get; set; } // Địa chỉ nhân viên, tối đa 50 ký tự

        [StringLength(20)]
        public string GioiTinh { get; set; } // Giới tính nhân viên, tối đa 20 ký tự

        [Column(TypeName = "char")]
        [StringLength(10)]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Số điện thoại không hợp lệ")]
        public string SDT { get; set; } // Số điện thoại, tối đa 10 ký tự, unique

        [Column(TypeName = "date")]
        public DateTime? NgayVaoLam { get; set; } // Ngày vào làm của nhân viên
    }
}

DoAnTotNghiep_WebMinhChau/Areas/Admin/Controllers/NhanVientController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnTotNghiep_WebMinhChau.Areas.Admin.Models;

namespace DoAnTotNghiep_WebMinhChau.Areas.Admin.Controllers
{
    public class NhanVientController : Controller
    {
        private Model1 db = new Model1();
        // GET: Admin/NhanVient
        public ActionResult NhanVien(string searchTerm)
        {
            ViewBag.SLNV = (int)db.Database.SqlQuery<int>("SELECT dbo.NV()").FirstOrDefault();
            var model = db.NhanVien.AsQueryable();
            if (!string.IsNullOrEmpty(searchTerm))
            {
                model = model.Where(dm => dm.HoTen.Contains(searchTerm));
            }
            return View(model.ToList());
        }

        // =============================================================================================== CHỈNH SỬA THÔNG TIN 
        public ActionResult Edit(string maNV)
        {
            if (string.IsNullOrWhiteSpace(maNV))
            {
                return HttpNotFound();
            }

            var nhanVien = db.NhanVien.Find(maNV);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }

            return View(nhanVien);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NhanVien nhanVien)
        {
            int currentYear = DateTime.Now.Year;
            if (nhanVien.NamSinh.HasValue && nhanVien.NamSinh > currentYear)
            {
                ModelState.AddModelError("NamSinh", "Năm sinh không được lớn hơn năm hiện tại.");
            }

            var existingPhone = db.NhanVien.FirstOrDefault(nv => nv.SDT == nhanVien.SDT && nv.MaNV != nhanVien.MaNV);
            if (existingPhone != null)
            {
                ModelState.AddModelError("SDT", "Số điện thoại này đã được sử dụng bởi nhân viên khác.");
            }
            if (!ModelState.IsValid)
            {
                return View(nhanVien);
            }

            var existingNhanVien = db.NhanVien.Find(nhanVien.MaNV);
            if (existingNhanVien == null)
            {
                ModelState.AddModelError("", "Nhân viên không tồn tại.");
                return View(nhanVien);
            }

            // Cập nhật thông tin nhân viên
            existingNhanVien.HoTen = nhanVien.HoTen;
            existingNhanVien.NamSinh = nhanVien.NamSinh;
            existingNhanVien.DiaChi = nhanVien.DiaChi;
            existingNhanVien.GioiTinh = nhanVien.GioiTinh;
            existingNhanVien.SDT = nhanVien.SDT;
            existingNhanVien.TrangThai = nhanVien.TrangThai;
            existingNhanVien.NgayVaoLam = nhanVien.NgayVaoLam;

            try
            {
                db.SaveChanges();
                return RedirectToAction("NhanVien");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Đã xảy ra lỗi khi lưu thay đổi. Vui lòng thử lại.");
                ModelState.AddModelError("", ex.Message);
                return View(nhanVien);
            }
        }

        // =============================================================================================== THÊM NHÂN VIÊN
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NhanVien nhanVien)
        {
            int currentYear = DateTime.Now.Year;
            if (nhanVien.NamSinh >= currentYear)
            {
                ModelState.AddModelError("NamSinh", "Năm sinh không được lớn hơn năm hiện tại.");
            }
            var existingPhone = db.NhanVien.FirstOrDefault(nv => nv.SDT == nhanVien.SDT && nv.MaNV != nhanVien.MaNV);
            if (existingPhone != null)
            {
                ModelState.AddModelError("SDT", "Số điện thoại này đã được sử dụng bởi nhân viên khác.");
            }
            if (!ModelState.IsValid)
            {
                return View(nhanVien);
            }
            var existingNhanVien = db.NhanVien.Find(nhanVien.MaNV);
            if (existingNhanVien != null)
            {
                ModelState.AddModelError("MaNV", "Mã nhân viên này đã tồn tại.");
            }
            if (!ModelState.IsValid)
            {
                return View(nhanVien);
            }

            db.NhanVien.Add(nhanVien);
            db.SaveChanges();
            return RedirectToAction("NhanVien");
        }


    }
}

DoAnTotNghiep_WebMinhChau/Areas/Admin/Views/NhanVient/Create.cshtml
@model DoAnTotNghiep_WebMinhChau.Areas.Admin.Models.NhanVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/LayoutADMIN.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container" style="max-width: 900px; margin: 30px auto;">

        <h2 class="text-center">Thêm nhân viên</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MaNV, "Mã nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, "Họ và tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamSinh, "Năm sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamSinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamSinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.GioiTinh, new List<SelectListItem>
                {
                    new SelectListItem { Text = "Nam", Value = "Nam" },
                    new SelectListItem { Text = "Nữ", Value = "Nữ" }
                }, "Chọn giới tính", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SDT, "Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TrangThai, new List<SelectListItem>
                {
                    new SelectListItem { Text = "Nhân viên mới", Value = "Nhân viên mới", Selected = true },
                    new SelectListItem { Text = "Nhân viên cũ", Value = "Nhân viên cũ" }
                }, "Chọn trạng thái", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NgayVaoLam, "Ngày vào làm", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NgayVaoLam, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                @Html.ValidationMessageFor(model => model.NgayVaoLam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="text-center">
    @Html.ActionLink("Trở về danh sách", "Index", null, new { @class = "btn btn-link" })
</div>

DoAnTotNghiep_WebMinhChau/Areas/Admin/Views/NhanVient/Edit.cshtml
@model DoAnTotNghiep_WebMinhChau.Areas.Admin.Models.NhanVien

@{
    ViewBag.Title = "Cập nhật thông tin nhân viên";
    Layout = "~/Areas/Admin/Views/Shared/LayoutADMIN.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container" style="max-width: 600px; margin-top: 30px;">
        <h2 class="text-center">Cập nhật thông tin nhân viên</h2>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            <label for="HoTen" class="control-label">Họ và tên</label>
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="NamSinh" class="control-label">Năm sinh</label>
            @Html.EditorFor(model => model.NamSinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NamSinh, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="DiaChi" class="control-label">Địa chỉ</label>
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="GioiTinh" class="control-label">Giới tính</label>
            @Html.DropDownListFor(model => model.GioiTinh, new List<SelectListItem>
            {
                new SelectListItem { Text = "Nam", Value = "Nam" },
                new SelectListItem { Text = "Nữ", Value = "Nữ" },
                new SelectListItem { Text = "Khác", Value = "Khác" }
            }, "Chọn giới tính", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="SDT" class="control-label">Số điện thoại</label>
            @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="TrangThai" class="control-label">Trạng thái</label>
            @Html.DropDownListFor(model => model.TrangThai, new List<SelectListItem>
            {
                new SelectListItem { Text = "Đang làm việc", Value = "Đang làm việc" },
                new SelectListItem { Text = "Đang thử việc", Value = "Đang thử việc" }
            }, "Chọn trạng thái", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="NgayVaoLam" class="control-label">Ngày vào làm</label>
            @Html.EditorFor(model => model.NgayVaoLam, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayVaoLam, "", new { @class = "text-danger" })
        </div>

        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary">Lưu</button>
        </div>

        <div class="text-center">
            @Html.ActionLink("Quay lại danh sách", "NhanVien", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
}

DoAnTotNghiep_WebMinhChau/Areas/Admin/Views/NhanVient/NhanVien.cshtml
@model IEnumerable<DoAnTotNghiep_WebMinhChau.Areas.Admin.Models.NhanVien>

@{
    ViewBag.Title = "NhanVien";
    Layout = "~/Areas/Admin/Views/Shared/LayoutADMIN.cshtml";
}

<style>
    .search-container {
        display: flex;
        align-items: center;
        max-width: 800px;
        margin: 20px auto;
    }

        .search-container input {
            flex: 1;
            padding: 8px 12px;
            border-radius: 20px 0 0 20px;
            border: 1px solid #ccc;
            border-right: none;
        }

        .search-container button {
            padding: 8px 16px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 0 20px 20px 0;
            cursor: pointer;
        }

    .actions {
        display: flex;
        align-items: center;
        margin-left: 20px;
    }

        .actions .create-new {
            background-color: #28a745;
            color: #fff;
            border: none;
            border-radius: 20px;
            padding: 6px 12px;
            margin-right: 10px;
            cursor: pointer;
        }

        .actions .count {
            background-color: #f8f9fa;
            border: 1px solid #ced4da;
            border-radius: 20px;
            padding: 6px 12px;
        }
</style>

<!-- Form tìm kiếm -->
<form class="search-container" method="get" action="@Url.Action("NhanVien", "NhanVient")">
    <input type="text" name="searchTerm" value="@Request.QueryString["searchTerm"]" placeholder="Tìm kiếm theo tên nhân viên" />
    <button type="submit">Tìm</button>
    <div class="actions">
        <button type="button" class="create-new btn btn-primary" onclick="window.location.href='@Url.Action("Create", "NhanVient")'">Thêm nhân viên</button>
        <div class="count">Số lượng nhân viên: @ViewBag.SLNV</div>
    </div>
</form>

<!-- Bảng hiển thị kết quả -->
<table class="table">
    <thead>
        <tr>
            <th>Mã NV</th>
            <th>Họ tên </th>
            <th>Ngày vào làm</th>
            <th>Địa chỉ</th>
            <th>Năm sinh</th>
            <th>Giới tính</th>
            <th>SĐT</th>
            <th>Trạng thái</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.MaNV)</td>
                    <td>@Html.DisplayFor(modelItem => item.HoTen)</td>
                    <td>@(item.NgayVaoLam?.ToString("dd/MM/yyyy") ?? "N/A")</td>
                    <td>@Html.DisplayFor(modelItem => item.DiaChi)</td>
                    <td>@Html.DisplayFor(modelItem => item.NamSinh)</td>
                    <td>@Html.DisplayFor(modelItem => item.GioiTinh)</td>
                    <td>@Html.DisplayFor(modelItem => item.SDT)</td>
                    <td>@Html.DisplayFor(modelItem => item.TrangThai)</td>
                    <td>
                        <a href="@Url.Action("Edit", "NhanVient", new { MaNV = item.MaNV })" class="btn-update btn btn-outline-info btn-sm me-2" ><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6">Không tìm thấy nhân viên nào</td>
            </tr>
        }
    </tbody>
</table>